---
apiVersion: v1
kind: Service
metadata:
  name: first-propagator
spec:
  selector:
    app: first-propagator
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: first-propagator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-propagator
  labels:
    app: first-propagator
    swimlane: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-propagator
      swimlane: default
  template:
    metadata:
      labels:
        app: first-propagator
        swimlane: default
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/service-tags: default
        consul.hashicorp.com/service-meta-swimlane: default
    spec:
      containers:
        - name: first-propagator
          image: nicholasjackson/fake-service:v0.7.8
          ports:
            - containerPort: 80
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:80'
            - name: 'NAME'
              value: 'first-propagator'
            - name: 'MESSAGE'
              value: 'first-propagator'
            - name: 'ALLOWED_HEADERS'
              value: 'x-swimlane'