#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: second-propagator
#spec:
#  selector:
#    app: second-propagator
#  ports:
#    - port: 80
#      targetPort: 80
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: second-propagator-sl1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-propagator-sl1
  labels:
    app: second-propagator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-propagator
  template:
    metadata:
      labels:
        app: second-propagator
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/service-tags: sl1
        consul.hashicorp.com/service-meta-swimlane: sl1
    spec:
      containers:
        - name: second-propagator
          image: nicholasjackson/fake-service:v0.7.8
          ports:
            - containerPort: 80
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:80'
            - name: 'NAME'
              value: 'second-propagator-sl1'
            - name: 'MESSAGE'
              value: 'second-propagator-sl1'
            - name: 'ALLOWED_HEADERS'
              value: 'x-swimlane'